import prisma from "./db.js";
import bcrypt from "bcryptjs";

const allCourses = [
    // --- WEB DEVELOPMENT ---
    {
        title: "HTML & CSS Full Course - Beginner to Pro",
        instructor: "SuperSimpleDev",
        thumbnail: "https://i.ytimg.com/vi/G3e-cpL7ofc/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/G3e-cpL7ofc",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "45K",
        duration: "6h 30m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.9,
        price: 0
    },
    {
        title: "JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour",
        instructor: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/W6NZfCO5SIk/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/W6NZfCO5SIk",
        studentsCount: 3200000,
        views: "3.2M",
        likes: "120K",
        duration: "1h 00m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.8,
        price: 0
    },
    {
        title: "React JS - React Tutorial for Beginners",
        instructor: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/Ke90Tje7VS0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Ke90Tje7VS0",
        studentsCount: 2100000,
        views: "2.1M",
        likes: "85K",
        duration: "2h 25m",
        level: "Intermediate",
        category: "Web Development",
        rating: 4.7,
        price: 0
    },
    {
        title: "Node.js and Express.js - Full Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/Oe421EPjeBE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Oe421EPjeBE",
        studentsCount: 950000,
        views: "950K",
        likes: "32K",
        duration: "8h 15m",
        level: "Advanced",
        category: "Web Development",
        rating: 4.8,
        price: 0
    },
    {
        title: "Full Stack Web Development for Beginners",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/Q33KBiDriJY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Q33KBiDriJY",
        studentsCount: 450000,
        views: "450K",
        likes: "15K",
        duration: "10h 30m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.6,
        price: 0
    },

    // --- GRAPHIC DESIGN ---
    {
        title: "Figma UI/UX Design Full Course",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/5c32g4pG1MA/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/5c32g4pG1MA",
        studentsCount: 2000000,
        views: "2M",
        likes: "60K",
        duration: "4h 00m",
        level: "Beginner",
        category: "Graphic Design",
        rating: 4.9,
        price: 0
    },
    {
        title: "Adobe Photoshop for Beginners | FREE COURSE",
        instructor: "Envato Tuts+",
        thumbnail: "https://i.ytimg.com/vi/IyR_uYsRdPs/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/IyR_uYsRdPs",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "40K",
        duration: "3h 10m",
        level: "Beginner",
        category: "Graphic Design",
        rating: 4.9,
        price: 0
    },
    {
        title: "Graphic Design Full Course - Beginner to Pro",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/s8k-qB6hS4U/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/s8k-qB6hS4U",
        studentsCount: 900000,
        views: "900K",
        likes: "35K",
        duration: "6h 30m",
        level: "All Levels",
        category: "Graphic Design",
        rating: 4.7,
        price: 0
    },

    // --- BUSINESS STRATEGY ---
    {
        title: "Project Management Full Course",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/5d169lT_4v4/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/5d169lT_4v4",
        studentsCount: 410000,
        views: "410K",
        likes: "12K",
        duration: "2h 00m",
        level: "Intermediate",
        category: "Business Strategy",
        rating: 4.6,
        price: 0
    },
    {
        title: "Entrepreneurship 101",
        instructor: "Harvard Innovation Labs",
        thumbnail: "https://i.ytimg.com/vi/lPh5h8I4F3I/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/lPh5h8I4F3I",
        studentsCount: 850000,
        views: "850K",
        likes: "25K",
        duration: "1h 15m",
        level: "Beginner",
        category: "Business Strategy",
        rating: 4.8,
        price: 0
    },

    // --- DIGITAL MARKETING ---
    {
        title: "Digital Marketing Course for Beginners",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/bixR-KIJKYM/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/bixR-KIJKYM",
        studentsCount: 500000,
        views: "500K",
        likes: "18K",
        duration: "2h 00m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.6,
        price: 0
    },
    {
        title: "SEO Tutorial for Beginners",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/DvwXlbfiwVQ/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/DvwXlbfiwVQ",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "40K",
        duration: "8h 30m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.8,
        price: 0
    },
    {
        title: "Google Ads Full Course",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/_0tT5_GvbIQ/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/_0tT5_GvbIQ",
        studentsCount: 600000,
        views: "600K",
        likes: "15K",
        duration: "5h 00m",
        level: "Intermediate",
        category: "Digital Marketing",
        rating: 4.7,
        price: 0
    },

    // --- MOBILE APPS ---
    {
        title: "React Native Tutorial for Beginners",
        instructor: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/0-S5a0eXPoc/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/0-S5a0eXPoc",
        studentsCount: 1800000,
        views: "1.8M",
        likes: "60K",
        duration: "2h 05m",
        level: "Beginner",
        category: "Mobile Apps",
        rating: 4.8,
        price: 0
    },
    {
        title: "Flutter for Beginners",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/VPvVD8t02U8/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/VPvVD8t02U8",
        studentsCount: 2000000,
        views: "2M",
        likes: "50K",
        duration: "37h 00m",
        level: "Beginner",
        category: "Mobile Apps",
        rating: 4.9,
        price: 0
    },
    {
        title: "Android Development for Beginners",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/fis26HvvDII/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/fis26HvvDII",
        studentsCount: 1100000,
        views: "1.1M",
        likes: "35K",
        duration: "11h 30m",
        level: "Intermediate",
        category: "Mobile Apps",
        rating: 4.8,
        price: 0
    },
    {
        title: "Swift Programming Tutorial for Beginners",
        instructor: "CodeWithChris",
        thumbnail: "https://i.ytimg.com/vi/F9UC9DY-vIU/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/F9UC9DY-vIU",
        studentsCount: 400000,
        views: "400K",
        likes: "12K",
        duration: "3h 15m",
        level: "Beginner",
        category: "Mobile Apps",
        rating: 4.7,
        price: 0
    },

    // --- DATA SCIENCE ---
    {
        title: "Data Science Full Course - Learn Data Science in 10 Hours",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/-ETQ97mXXF0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/-ETQ97mXXF0",
        studentsCount: 2500000,
        views: "2.5M",
        likes: "75K",
        duration: "10h 00m",
        level: "Beginner",
        category: "Data Science",
        rating: 4.8,
        price: 0
    },
    {
        title: "Python for Data Science - Course for Beginners",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/LHBE6Q9XlzI/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/LHBE6Q9XlzI",
        studentsCount: 3000000,
        views: "3M",
        likes: "95K",
        duration: "12h 00m",
        level: "Intermediate",
        category: "Data Science",
        rating: 4.9,
        price: 0
    },
    {
        title: "Statistics for Data Science",
        instructor: "Great Learning",
        thumbnail: "https://i.ytimg.com/vi/Vfo5le26IhY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Vfo5le26IhY",
        studentsCount: 800000,
        views: "800K",
        likes: "20K",
        duration: "4h 30m",
        level: "Intermediate",
        category: "Data Science",
        rating: 4.7,
        price: 0
    },
    {
        title: "Data Analysis with Python - Full Course for Beginners",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/r-uOLxNrNk8/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/r-uOLxNrNk8",
        studentsCount: 3000000,
        views: "3M",
        likes: "85K",
        duration: "4h 30m",
        level: "Intermediate",
        category: "Data Science",
        rating: 4.8,
        price: 0
    },
    {
        title: "Machine Learning with Python",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/ukzFI9rgwfU/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/ukzFI9rgwfU",
        studentsCount: 650000,
        views: "650K",
        likes: "18K",
        duration: "8h 00m",
        level: "Advanced",
        category: "Data Science",
        rating: 4.7,
        price: 0
    },

    // --- CYBERSECURITY ---
    {
        title: "Ethical Hacking Full Course - Learn Ethical Hacking in 12 Hours",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/3Kq1MIfTWCE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/3Kq1MIfTWCE",
        studentsCount: 2000000,
        views: "2M",
        likes: "60K",
        duration: "12h 00m",
        level: "Beginner",
        category: "Cybersecurity",
        rating: 4.8,
        price: 0
    },
    {
        title: "Cyber Security Full Course",
        instructor: "Great Learning",
        thumbnail: "https://i.ytimg.com/vi/fS6eNf9XvFk/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/fS6eNf9XvFk",
        studentsCount: 3500000,
        views: "3.5M",
        likes: "125K",
        duration: "11h 30m",
        level: "Beginner",
        category: "Cybersecurity",
        rating: 4.9,
        price: 0
    },
    {
        title: "Ethical Hacking Course",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/dz7Ntp7KQGA/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/dz7Ntp7KQGA",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "40K",
        duration: "4h 00m",
        level: "Intermediate",
        category: "Cybersecurity",
        rating: 4.9,
        price: 0
    },
    {
        title: "Network Security Tutorial",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/qiQR5rTSshw/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/qiQR5rTSshw",
        studentsCount: 400000,
        views: "400K",
        likes: "12K",
        duration: "5h 30m",
        level: "Intermediate",
        category: "Cybersecurity",
        rating: 4.7,
        price: 0
    },
    {
        title: "Penetration Testing | Ethical Hacking Tutorial",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/fNz8ykqJltc/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/fNz8ykqJltc",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "45K",
        duration: "1h 30m",
        level: "Advanced",
        category: "Cybersecurity",
        rating: 4.8,
        price: 0
    },

    // --- ARTIFICIAL INTELLIGENCE ---
    {
        title: "Artificial Intelligence Full Course | AI Tutorial for Beginners",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/JMUxmLyrhSk/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/JMUxmLyrhSk",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "40K",
        duration: "4h 30m",
        level: "Beginner",
        category: "Artificial Intelligence",
        rating: 4.8,
        price: 0
    },
    {
        title: "Machine Learning Full Course",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/GwIoJAO7M6k/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/GwIoJAO7M6k",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "35K",
        duration: "10h 00m",
        level: "Intermediate",
        category: "Artificial Intelligence",
        rating: 4.8,
        price: 0
    },
    {
        title: "Deep Learning Crash Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/VyWAvY2CF9c/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/VyWAvY2CF9c",
        studentsCount: 500000,
        views: "500K",
        likes: "15K",
        duration: "3h 45m",
        level: "Advanced",
        category: "Artificial Intelligence",
        rating: 4.9,
        price: 0
    },
    {
        title: "Neural Networks from Scratch",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/Wo5dMEP_BbI/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Wo5dMEP_BbI",
        studentsCount: 4000000,
        views: "4M",
        likes: "150K",
        duration: "4h 00m",
        level: "Advanced",
        category: "Artificial Intelligence",
        rating: 5.0,
        price: 0
    },
    {
        title: "TensorFlow 2.0 Complete Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/tPYj3fFJGjk/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/tPYj3fFJGjk",
        studentsCount: 300000,
        views: "300K",
        likes: "12K",
        duration: "14h 00m",
        level: "Intermediate",
        category: "Artificial Intelligence",
        rating: 4.7,
        price: 0
    },

    // --- CLOUD COMPUTING ---
    {
        title: "Cloud Computing Full Course | Cloud Computing Tutorial",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/M988_fsOSWo/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/M988_fsOSWo",
        studentsCount: 2000000,
        views: "2M",
        likes: "50K",
        duration: "3h 00m",
        level: "Beginner",
        category: "Cloud Computing",
        rating: 4.8,
        price: 0
    },
    {
        title: "AWS Certified Cloud Practitioner - Full Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/3hLmDS179YE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/3hLmDS179YE",
        studentsCount: 2000000,
        views: "2M",
        likes: "60K",
        duration: "13h 00m",
        level: "Beginner",
        category: "Cloud Computing",
        rating: 4.9,
        price: 0
    },
    {
        title: "Azure Fundamentals Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/NKEFWyqJ5dy/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/NKEFWyqJ5dy",
        studentsCount: 800000,
        views: "800K",
        likes: "25K",
        duration: "8h 30m",
        level: "Intermediate",
        category: "Cloud Computing",
        rating: 4.8,
        price: 0
    },
    {
        title: "Google Cloud Digital Leader Certification",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/U9k6k4o1kQo/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/U9k6k4o1kQo",
        studentsCount: 600000,
        views: "600K",
        likes: "18K",
        duration: "6h 00m",
        level: "Intermediate",
        category: "Cloud Computing",
        rating: 4.7,
        price: 0
    },
    {
        title: "Docker & Kubernetes Tutorial",
        instructor: "TechWorld with Nana",
        thumbnail: "https://i.ytimg.com/vi/3c-iBn73dDE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/3c-iBn73dDE",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "45K",
        duration: "3h 30m",
        level: "Advanced",
        category: "Cloud Computing",
        rating: 4.9,
        price: 0
    },
    // --- HINDI COURSES ---
    {
        title: "JavaScript Tutorial in Hindi",
        instructor: "CodeWithHarry",
        thumbnail: "https://i.ytimg.com/vi/hKB-YGF14SY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/hKB-YGF14SY",
        studentsCount: 5000000,
        views: "5M",
        likes: "200K",
        duration: "20h 00m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.9,
        price: 0
    },
    {
        title: "React JS Tutorial in Hindi",
        instructor: "CodeWithHarry",
        thumbnail: "https://i.ytimg.com/vi/-mJFZp84TIY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/-mJFZp84TIY",
        studentsCount: 3000000,
        views: "3M",
        likes: "150K",
        duration: "15h 30m",
        level: "Intermediate",
        category: "Web Development",
        rating: 4.8,
        price: 0
    },
    {
        title: "Python Tutorial in Hindi",
        instructor: "CodeWithHarry",
        thumbnail: "https://i.ytimg.com/vi/gfDE2a7MKjA/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/gfDE2a7MKjA",
        studentsCount: 8000000,
        views: "8M",
        likes: "300K",
        duration: "12h 00m",
        level: "Beginner",
        category: "Programming",
        rating: 4.9,
        price: 0
    },
    {
        title: "Java Tutorial in Hindi",
        instructor: "Apna College",
        thumbnail: "https://i.ytimg.com/vi/yRpLlJmRo2w/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/yRpLlJmRo2w",
        studentsCount: 6000000,
        views: "6M",
        likes: "250K",
        duration: "10h 30m",
        level: "Beginner",
        category: "Programming",
        rating: 4.8,
        price: 0
    },
    {
        title: "C++ Placement Course in Hindi",
        instructor: "CodeHelp - by Babbar",
        thumbnail: "https://i.ytimg.com/vi/WQoB2z67hvY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/WQoB2z67hvY",
        studentsCount: 4500000,
        views: "4.5M",
        likes: "200K",
        duration: "25h 00m",
        level: "Advanced",
        category: "Programming",
        rating: 4.9,
        price: 0
    },
    {
        title: "DSA using Java in Hindi",
        instructor: "Apna College",
        thumbnail: "https://i.ytimg.com/vi/V8qGqE5d5Mo/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/V8qGqE5d5Mo",
        studentsCount: 3500000,
        views: "3.5M",
        likes: "180K",
        duration: "45h 00m",
        level: "Intermediate",
        category: "Programming",
        rating: 4.9,
        price: 0
    },
    {
        title: "Android App Development in Hindi",
        instructor: "CodeWithHarry",
        thumbnail: "https://i.ytimg.com/vi/InigF9uJHMs/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/InigF9uJHMs",
        studentsCount: 2200000,
        views: "2.2M",
        likes: "90K",
        duration: "30h 00m",
        level: "Intermediate",
        category: "Mobile Apps",
        rating: 4.8,
        price: 0
    },
    {
        title: "Machine Learning Course in Hindi",
        instructor: "CodeWithHarry",
        thumbnail: "https://i.ytimg.com/vi/7eh4d6sabA0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/7eh4d6sabA0",
        studentsCount: 1800000,
        views: "1.8M",
        likes: "75K",
        duration: "18h 00m",
        level: "Advanced",
        category: "Data Science",
        rating: 4.8,
        price: 0
    },
    {
        title: "PHP Tutorial for Beginners in Hindi",
        instructor: "Yahoo Baba",
        thumbnail: "https://i.ytimg.com/vi/xW7ro3lHkxM/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/xW7ro3lHkxM",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "40K",
        duration: "8h 00m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.7,
        price: 0
    },
    {
        title: "SQL Tutorial in Hindi",
        instructor: "CodeWithHarry",
        thumbnail: "https://i.ytimg.com/vi/BPHAr4QGGVE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/BPHAr4QGGVE",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "60K",
        duration: "5h 30m",
        level: "Beginner",
        category: "Data Science",
        rating: 4.8,
        price: 0
    },
    // --- ADDITIONAL WEB DEVELOPMENT COURSES (Total now 10+) ---
    {
        title: "Vue.js 3 Tutorial for Beginners",
        instructor: "Net Ninja",
        thumbnail: "https://i.ytimg.com/vi/Yrk4rVdF16U/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Yrk4rVdF16U",
        studentsCount: 900000,
        views: "900K",
        likes: "35K",
        duration: "4h 00m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.8,
        price: 0
    },
    {
        title: "Angular Full Course for Beginners",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/2OHbjep_WjQ/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/2OHbjep_WjQ",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "40K",
        duration: "6h 00m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.7,
        price: 0
    },
    {
        title: "Bootstrap 5 Tutorial",
        instructor: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/4sosXZsdy-s/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/4sosXZsdy-s",
        studentsCount: 800000,
        views: "800K",
        likes: "30K",
        duration: "1h 30m",
        level: "Beginner",
        category: "Web Development",
        rating: 4.8,
        price: 0
    },
    {
        title: "Django Tutorial for Beginners",
        instructor: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/rHux0gMz3Eg/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/rHux0gMz3Eg",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "50K",
        duration: "1h 00m",
        level: "Intermediate",
        category: "Web Development",
        rating: 4.7,
        price: 0
    },

    // --- ADDITIONAL GRAPHIC DESIGN COURSES ---
    {
        title: "Illustrator 2024 MasterClass",
        instructor: "Envato Tuts+",
        thumbnail: "https://i.ytimg.com/vi/Ib8UBwu3yGA/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Ib8UBwu3yGA",
        studentsCount: 500000,
        views: "500K",
        likes: "20K",
        duration: "3h 30m",
        level: "Beginner",
        category: "Graphic Design",
        rating: 4.9,
        price: 0
    },
    {
        title: "Canva Tutorial for Beginners",
        instructor: "Technology for Teachers and Students",
        thumbnail: "https://i.ytimg.com/vi/un50Bs4BvZ8/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/un50Bs4BvZ8",
        studentsCount: 3000000,
        views: "3M",
        likes: "80K",
        duration: "1h 00m",
        level: "Beginner",
        category: "Graphic Design",
        rating: 4.8,
        price: 0
    },
    {
        title: "Logo Design Masterclass",
        instructor: "Gareth David",
        thumbnail: "https://i.ytimg.com/vi/5v6WgyE6eH8/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/5v6WgyE6eH8",
        studentsCount: 600000,
        views: "600K",
        likes: "25K",
        duration: "45m",
        level: "Intermediate",
        category: "Graphic Design",
        rating: 4.7,
        price: 0
    },
    {
        title: "UI Design Crash Course",
        instructor: "DesignCourse",
        thumbnail: "https://i.ytimg.com/vi/1rA_c4aR6Ks/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/1rA_c4aR6Ks",
        studentsCount: 400000,
        views: "400K",
        likes: "15K",
        duration: "1h 45m",
        level: "Intermediate",
        category: "Graphic Design",
        rating: 4.8,
        price: 0
    },
    {
        title: "Adobe InDesign for Beginners",
        instructor: "Envato Tuts+",
        thumbnail: "https://i.ytimg.com/vi/EfgjVpE1t6w/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/EfgjVpE1t6w",
        studentsCount: 300000,
        views: "300K",
        likes: "10K",
        duration: "2h 30m",
        level: "Beginner",
        category: "Graphic Design",
        rating: 4.7,
        price: 0
    },
    {
        title: "Color Theory for Designers",
        instructor: "Gareth David",
        thumbnail: "https://i.ytimg.com/vi/AvgCkHrcj90/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/AvgCkHrcj90",
        studentsCount: 800000,
        views: "800K",
        likes: "35K",
        duration: "30m",
        level: "All Levels",
        category: "Graphic Design",
        rating: 4.9,
        price: 0
    },
    {
        title: "Typography Tutorial - 10 Rules to Help You Rule Type",
        instructor: "The Futur",
        thumbnail: "https://i.ytimg.com/vi/QrNi9FmdLxY/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/QrNi9FmdLxY",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "70K",
        duration: "15m",
        level: "All Levels",
        category: "Graphic Design",
        rating: 4.9,
        price: 0
    },

    // --- ADDITIONAL BUSINESS STRATEGY COURSES ---
    {
        title: "Product Management for Beginners",
        instructor: "Product School",
        thumbnail: "https://i.ytimg.com/vi/JeD6l-B9f1I/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/JeD6l-B9f1I",
        studentsCount: 400000,
        views: "400K",
        likes: "12K",
        duration: "1h 30m",
        level: "Beginner",
        category: "Business Strategy",
        rating: 4.7,
        price: 0
    },
    {
        title: "Marketing Strategy - The Fundamentals",
        instructor: "HubSpot Marketing",
        thumbnail: "https://i.ytimg.com/vi/eG9rF42Rdfw/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/eG9rF42Rdfw",
        studentsCount: 600000,
        views: "600K",
        likes: "20K",
        duration: "45m",
        level: "Beginner",
        category: "Business Strategy",
        rating: 4.8,
        price: 0
    },
    {
        title: "Financial Literacy - Full Course",
        instructor: "Practical Wisdom - Interesting History",
        thumbnail: "https://i.ytimg.com/vi/yl_lM7_qj3Y/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/yl_lM7_qj3Y",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "50K",
        duration: "2h 15m",
        level: "Beginner",
        category: "Business Strategy",
        rating: 4.9,
        price: 0
    },
    {
        title: "Business Communication Skills",
        instructor: "Communication Coach Alexander Lyon",
        thumbnail: "https://i.ytimg.com/vi/XzM04iWv9F0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/XzM04iWv9F0",
        studentsCount: 500000,
        views: "500K",
        likes: "18K",
        duration: "30m",
        level: "Intermediate",
        category: "Business Strategy",
        rating: 4.7,
        price: 0
    },
    {
        title: "Agile Methodology Tutorial",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/Z9QbOq3iC9c/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Z9QbOq3iC9c",
        studentsCount: 900000,
        views: "900K",
        likes: "25K",
        duration: "1h 00m",
        level: "Beginner",
        category: "Business Strategy",
        rating: 4.6,
        price: 0
    },
    {
        title: "Leadership Skills for Managers",
        instructor: "Brian Tracy",
        thumbnail: "https://i.ytimg.com/vi/N6D3yQjXkYc/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/N6D3yQjXkYc",
        studentsCount: 700000,
        views: "700K",
        likes: "30K",
        duration: "20m",
        level: "Intermediate",
        category: "Business Strategy",
        rating: 4.8,
        price: 0
    },
    {
        title: "Start a Business in 10 Days",
        instructor: "Pat Flynn",
        thumbnail: "https://i.ytimg.com/vi/MgY0a6F0c-k/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/MgY0a6F0c-k",
        studentsCount: 300000,
        views: "300K",
        likes: "15K",
        duration: "2h 45m",
        level: "Beginner",
        category: "Business Strategy",
        rating: 4.7,
        price: 0
    },
    {
        title: "Strategic Planning - Overview",
        instructor: "GreggU",
        thumbnail: "https://i.ytimg.com/vi/q_M6uHhL8gE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/q_M6uHhL8gE",
        studentsCount: 200000,
        views: "200K",
        likes: "5K",
        duration: "15m",
        level: "Advanced",
        category: "Business Strategy",
        rating: 4.5,
        price: 0
    },

    // --- ADDITIONAL DIGITAL MARKETING COURSES ---
    {
        title: "Social Media Marketing Full Course",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/nU-IIXJLK_g/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/nU-IIXJLK_g",
        studentsCount: 800000,
        views: "800K",
        likes: "30K",
        duration: "5h 00m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.8,
        price: 0
    },
    {
        title: "Facebook Ads Tutorial",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/SFy44EaC4g0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/SFy44EaC4g0",
        studentsCount: 600000,
        views: "600K",
        likes: "20K",
        duration: "4h 00m",
        level: "Intermediate",
        category: "Digital Marketing",
        rating: 4.7,
        price: 0
    },
    {
        title: "Content Marketing Course",
        instructor: "HubSpot Academy",
        thumbnail: "https://i.ytimg.com/vi/o4o6s1GgRFA/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/o4o6s1GgRFA",
        studentsCount: 400000,
        views: "400K",
        likes: "15K",
        duration: "3h 30m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.9,
        price: 0
    },
    {
        title: "Email Marketing for Beginners",
        instructor: "H-EDUCATE",
        thumbnail: "https://i.ytimg.com/vi/1X9X9X9X9X9/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/TqXwb_H7k4s",
        studentsCount: 250000,
        views: "250K",
        likes: "10K",
        duration: "1h 00m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.6,
        price: 0
    },
    {
        title: "Affiliate Marketing Tutorial",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/ca_1o_3tT80/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/ca_1o_3tT80",
        studentsCount: 500000,
        views: "500K",
        likes: "18K",
        duration: "2h 00m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.7,
        price: 0
    },
    {
        title: "Instagram Marketing Strategy",
        instructor: "Adam Erhart",
        thumbnail: "https://i.ytimg.com/vi/XXXX9X9X9X9/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/d3_1g4qb9O0",
        studentsCount: 700000,
        views: "700K",
        likes: "25K",
        duration: "20m",
        level: "Intermediate",
        category: "Digital Marketing",
        rating: 4.8,
        price: 0
    },
    {
        title: "Copywriting for Beginners",
        instructor: "Alex Cattoni",
        thumbnail: "https://i.ytimg.com/vi/XXXX9X9X9X9/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/XXXX9X9X9X9",
        studentsCount: 300000,
        views: "300K",
        likes: "12K",
        duration: "15m",
        level: "Beginner",
        category: "Digital Marketing",
        rating: 4.8,
        price: 0
    },
    // --- ADDITIONAL MOBILE APPS COURSES ---
    {
        title: "Kotlin Course - Tutorial for Beginners",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/F9UC9DY-vIU/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/F9UC9DY-vIU",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "40K",
        duration: "2h 30m",
        level: "Beginner",
        category: "Mobile Apps",
        rating: 4.8,
        price: 0
    },
    {
        title: "iOS Development with Swift - Full Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/Com_Q2o0sT0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Com_Q2o0sT0",
        studentsCount: 800000,
        views: "800K",
        likes: "30K",
        duration: "5h 00m",
        level: "Beginner",
        category: "Mobile Apps",
        rating: 4.9,
        price: 0
    },
    {
        title: "React Native Crash Course",
        instructor: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/Hf4c8Dr-kwM/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Hf4c8Dr-kwM",
        studentsCount: 600000,
        views: "600K",
        likes: "25K",
        duration: "2h 00m",
        level: "Intermediate",
        category: "Mobile Apps",
        rating: 4.8,
        price: 0
    },
    {
        title: "Build an App in 10 Minutes (No Code)",
        instructor: "Glide",
        thumbnail: "https://i.ytimg.com/vi/XXXX9X9X9X9/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/XXXX9X9X9X9",
        studentsCount: 400000,
        views: "400K",
        likes: "10K",
        duration: "10m",
        level: "Beginner",
        category: "Mobile Apps",
        rating: 4.6,
        price: 0
    },
    {
        title: "Ionic Framework Tutorial",
        instructor: "Academind",
        thumbnail: "https://i.ytimg.com/vi/r2ga-iXS5iE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/r2ga-iXS5iE",
        studentsCount: 300000,
        views: "300K",
        likes: "12K",
        duration: "1h 30m",
        level: "Intermediate",
        category: "Mobile Apps",
        rating: 4.7,
        price: 0
    },
    {
        title: "Xamarin Forms Tutorial",
        instructor: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/w2WjN_a2Wrc/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/w2WjN_a2Wrc",
        studentsCount: 400000,
        views: "400K",
        likes: "15K",
        duration: "1h 00m",
        level: "Intermediate",
        category: "Mobile Apps",
        rating: 4.6,
        price: 0
    },

    // --- ADDITIONAL DATA SCIENCE COURSES ---
    {
        title: "R Programming Tutorial",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/_V8eKsto3Ug/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/_V8eKsto3Ug",
        studentsCount: 1100000,
        views: "1.1M",
        likes: "35K",
        duration: "2h 00m",
        level: "Beginner",
        category: "Data Science",
        rating: 4.8,
        price: 0
    },
    {
        title: "Tableau Full Course",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/aHaOIvIy0Dk/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/aHaOIvIy0Dk",
        studentsCount: 800000,
        views: "800K",
        likes: "25K",
        duration: "4h 00m",
        level: "Beginner",
        category: "Data Science",
        rating: 4.7,
        price: 0
    },
    {
        title: "Excel for Data Analysis",
        instructor: "Kevin Stratvert",
        thumbnail: "https://i.ytimg.com/vi/OatUb8S2qpc/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/OatUb8S2qpc",
        studentsCount: 2000000,
        views: "2M",
        likes: "60K",
        duration: "1h 00m",
        level: "Beginner",
        category: "Data Science",
        rating: 4.9,
        price: 0
    },
    {
        title: "Power BI Full Course",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/3u7JBn1R7Fk/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/3u7JBn1R7Fk",
        studentsCount: 900000,
        views: "900K",
        likes: "30K",
        duration: "3h 30m",
        level: "Beginner",
        category: "Data Science",
        rating: 4.8,
        price: 0
    },
    {
        title: "Big Data & Hadoop Full Course",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/1vbXmCrkT3Y/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/1vbXmCrkT3Y",
        studentsCount: 500000,
        views: "500K",
        likes: "15K",
        duration: "10h 00m",
        level: "Advanced",
        category: "Data Science",
        rating: 4.7,
        price: 0
    },

    // --- ADDITIONAL CYBERSECURITY COURSES ---
    {
        title: "Linux for Ethical Hackers",
        instructor: "NetworkChuck",
        thumbnail: "https://i.ytimg.com/vi/lZAoFs75_cs/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/lZAoFs75_cs",
        studentsCount: 900000,
        views: "900K",
        likes: "40K",
        duration: "20m",
        level: "Beginner",
        category: "Cybersecurity",
        rating: 4.9,
        price: 0
    },
    {
        title: "CompTIA Security+ Full Course",
        instructor: "Professor Messer",
        thumbnail: "https://i.ytimg.com/vi/9g8-f7t7_f4/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/9g8-f7t7_f4",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "50K",
        duration: "12h 00m",
        level: "Beginner",
        category: "Cybersecurity",
        rating: 4.9,
        price: 0
    },
    {
        title: "Wireshark Tutorial for Beginners",
        instructor: "The Networking Doctor",
        thumbnail: "https://i.ytimg.com/vi/lb1Dw0elIGg/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/lb1Dw0elIGg",
        studentsCount: 300000,
        views: "300K",
        likes: "10K",
        duration: "30m",
        level: "Intermediate",
        category: "Cybersecurity",
        rating: 4.7,
        price: 0
    },
    {
        title: "Cryptography Full Course",
        instructor: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/jhXCTbFnK8o/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/jhXCTbFnK8o",
        studentsCount: 400000,
        views: "400K",
        likes: "12K",
        duration: "3h 00m",
        level: "Advanced",
        category: "Cybersecurity",
        rating: 4.8,
        price: 0
    },
    {
        title: "Bug Bounty Hunting for Beginners",
        instructor: "HackerSploit",
        thumbnail: "https://i.ytimg.com/vi/h2-9b7T3p_Q/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/h2-9b7T3p_Q",
        studentsCount: 500000,
        views: "500K",
        likes: "25K",
        duration: "45m",
        level: "Intermediate",
        category: "Cybersecurity",
        rating: 4.8,
        price: 0
    },

    // --- ADDITIONAL AI COURSES ---
    {
        title: "Python for Artificial Intelligence",
        instructor: "FreeCodeCamp",
        thumbnail: "https://i.ytimg.com/vi/Wtr5rO6t_eE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/Wtr5rO6t_eE",
        studentsCount: 800000,
        views: "800K",
        likes: "30K",
        duration: "3h 00m",
        level: "Beginner",
        category: "Artificial Intelligence",
        rating: 4.8,
        price: 0
    },
    {
        title: "Chatbots with Python (NLTK)",
        instructor: "Tech With Tim",
        thumbnail: "https://i.ytimg.com/vi/wTJHwp086_w/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/wTJHwp086_w",
        studentsCount: 400000,
        views: "400K",
        likes: "15K",
        duration: "40m",
        level: "Intermediate",
        category: "Artificial Intelligence",
        rating: 4.7,
        price: 0
    },
    {
        title: "Computer Vision with OpenCV",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/oXlwWbU8l2o/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/oXlwWbU8l2o",
        studentsCount: 1200000,
        views: "1.2M",
        likes: "45K",
        duration: "3h 00m",
        level: "Advanced",
        category: "Artificial Intelligence",
        rating: 4.9,
        price: 0
    },
    {
        title: "Natural Language Processing (NLP)",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/CMrHM8a3hqw/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/CMrHM8a3hqw",
        studentsCount: 600000,
        views: "600K",
        likes: "20K",
        duration: "1h 30m",
        level: "Advanced",
        category: "Artificial Intelligence",
        rating: 4.8,
        price: 0
    },
    {
        title: "Reinforcement Learning Course",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/JgvyzIkgxF0/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/JgvyzIkgxF0",
        studentsCount: 200000,
        views: "200K",
        likes: "8K",
        duration: "2h 30m",
        level: "Advanced",
        category: "Artificial Intelligence",
        rating: 4.7,
        price: 0
    },

    // --- ADDITIONAL CLOUD COURSES ---
    {
        title: "DevOps Tutorial for Beginners",
        instructor: "Nana",
        thumbnail: "https://i.ytimg.com/vi/XXXX9X9X9X9/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/XXXX9X9X9X9",
        studentsCount: 1500000,
        views: "1.5M",
        likes: "50K",
        duration: "1h 00m",
        level: "Beginner",
        category: "Cloud Computing",
        rating: 4.9,
        price: 0
    },
    {
        title: "Terraform Course for Beginners",
        instructor: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/SLB_c_ayRMo/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/SLB_c_ayRMo",
        studentsCount: 800000,
        views: "800K",
        likes: "25K",
        duration: "2h 00m",
        level: "Intermediate",
        category: "Cloud Computing",
        rating: 4.8,
        price: 0
    },
    {
        title: "Ansible Vs Terraform",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/YfJO2Wd0d0M/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/YfJO2Wd0d0M",
        studentsCount: 300000,
        views: "300K",
        likes: "10K",
        duration: "30m",
        level: "Intermediate",
        category: "Cloud Computing",
        rating: 4.6,
        price: 0
    },
    {
        title: "Jenkins Tutorial for Beginners",
        instructor: "Edureka",
        thumbnail: "https://i.ytimg.com/vi/LFDrDnJHuyg/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/LFDrDnJHuyg",
        studentsCount: 600000,
        views: "600K",
        likes: "18K",
        duration: "45m",
        level: "Beginner",
        category: "Cloud Computing",
        rating: 4.7,
        price: 0
    },
    {
        title: "Introduction to Microservices",
        instructor: "SmartCode",
        thumbnail: "https://i.ytimg.com/vi/1xo-0gCVhRE/hqdefault.jpg",
        videoUrl: "https://www.youtube.com/embed/1xo-0gCVhRE",
        studentsCount: 400000,
        views: "400K",
        likes: "15K",
        duration: "40m",
        level: "Advanced",
        category: "Cloud Computing",
        rating: 4.8,
        price: 0
    },
];


const seedCourses = async () => {
    console.log("🌱 Seeding courses...");

    // 1. Ensure a default instructor user exists
    const email = "instructor@learnflow.com";
    let instructor = await prisma.user.findUnique({ where: { email } });

    if (!instructor) {
        const hashedPassword = await bcrypt.hash("password123", 10);
        instructor = await prisma.user.create({
            data: {
                name: "LearnFlow Instructor",
                email,
                password: hashedPassword,
                role: "instructor",
            },
        });
        console.log("✅ Created default instructor user");
    }

    // 2. Loop and upsert courses
    for (const courseData of allCourses) {
        // We check if a course with this title already exists to avoid duplicates
        // Since title isn't @unique in schema, we use findFirst
        const existing = await prisma.course.findFirst({
            where: { title: courseData.title }
        });

        if (!existing) {
            await prisma.course.create({
                data: {
                    title: courseData.title,
                    description: `Learn ${courseData.title} completely free.`,
                    price: courseData.price,
                    videoUrl: courseData.videoUrl,
                    thumbnail: courseData.thumbnail,
                    rating: parseFloat(courseData.rating),
                    studentsCount: courseData.studentsCount,
                    views: courseData.views,
                    likesCount: courseData.likes, // Map 'likes' from data array to 'likesCount' in DB
                    duration: courseData.duration,
                    level: courseData.level,
                    category: courseData.category,
                    instructorName: courseData.instructor, // Store the display string here
                    instructorId: instructor.id, // Link to the 'owner' user
                    hidden: false
                }
            });
            console.log(`+ Added: ${courseData.title}`);
        } else {
            console.log(`= Skipped (exists): ${courseData.title}`);
        }
    }

    console.log("✅ Seeding completed!");
};

seedCourses()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
